In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("D:\Projects\Datasets\PCOS_data\PCOS_data.csv")

In [3]:
df.head()

Sl. No  Patient File No.  PCOS (Y/N)   Age (yrs)  Weight (Kg)  Height(Cm)   \
0       1                 1           0          28         44.6        152.0   
1       2                 2           0          36         65.0        161.5   
2       3                 3           1          33         68.8        165.0   
3       4                 4           0          37         65.0        148.0   
4       5                 5           0          25         52.0        161.0   

    BMI  Blood Group  Pulse rate(bpm)   RR (breaths/min)  ...  \
0  19.3           15                78                22  ...   
1  24.9           15                74                20  ...   
2  25.3           11                72                18  ...   
3  29.7           13                72                20  ...   
4  20.1           11                72                18  ...   

   Fast food (Y/N)  Reg.Exercise(Y/N)  BP _Systolic (mmHg)  \
0              1.0                  0                  110   
1              0.0                  0                  120   
2              1.0                  0                  120   
3              0.0                  0                  120   
4              0.0                  0                  120   

   BP _Diastolic (mmHg)  Follicle No. (L)  Follicle No. (R)  \
0                    80                 3                 3   
1                    70                 3                 5   
2                    80                13                15   
3                    70                 2                 2   
4                    80                 3                 4   

   Avg. F size (L) (mm) Avg. F size (R) (mm)  Endometrium (mm)  Unnamed: 44  
0                  18.0                 18.0               8.5          NaN  
1                  15.0                 14.0               3.7          NaN  
2                  18.0                 20.0              10.0          NaN  
3                  15.0                 14.0               7.5          NaN  
4                  16.0                 14.0               7.0          NaN  

[5 rows x 45 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 45 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Sl. No                  541 non-null    int64  
 1   Patient File No.        541 non-null    int64  
 2   PCOS (Y/N)              541 non-null    int64  
 3    Age (yrs)              541 non-null    int64  
 4   Weight (Kg)             541 non-null    float64
 5   Height(Cm)              541 non-null    float64
 6   BMI                     541 non-null    float64
 7   Blood Group             541 non-null    int64  
 8   Pulse rate(bpm)         541 non-null    int64  
 9   RR (breaths/min)        541 non-null    int64  
 10  Hb(g/dl)                541 non-null    float64
 11  Cycle(R/I)              541 non-null    int64  
 12  Cycle length(days)      541 non-null    int64  
 13  Marraige Status (Yrs)   540 non-null    float64
 14  Pregnant(Y/N)           541 non-null    in

In [5]:
df = df.drop(['Sl. No', 'Patient File No.', 'Unnamed: 44', 'II    beta-HCG(mIU/mL)', 'AMH(ng/mL)'],axis=1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 40 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   PCOS (Y/N)              541 non-null    int64  
 1    Age (yrs)              541 non-null    int64  
 2   Weight (Kg)             541 non-null    float64
 3   Height(Cm)              541 non-null    float64
 4   BMI                     541 non-null    float64
 5   Blood Group             541 non-null    int64  
 6   Pulse rate(bpm)         541 non-null    int64  
 7   RR (breaths/min)        541 non-null    int64  
 8   Hb(g/dl)                541 non-null    float64
 9   Cycle(R/I)              541 non-null    int64  
 10  Cycle length(days)      541 non-null    int64  
 11  Marraige Status (Yrs)   540 non-null    float64
 12  Pregnant(Y/N)           541 non-null    int64  
 13  No. of abortions        541 non-null    int64  
 14    I   beta-HCG(mIU/mL)  541 non-null    fl

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 40 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   PCOS (Y/N)              541 non-null    int64  
 1    Age (yrs)              541 non-null    int64  
 2   Weight (Kg)             541 non-null    float64
 3   Height(Cm)              541 non-null    float64
 4   BMI                     541 non-null    float64
 5   Blood Group             541 non-null    int64  
 6   Pulse rate(bpm)         541 non-null    int64  
 7   RR (breaths/min)        541 non-null    int64  
 8   Hb(g/dl)                541 non-null    float64
 9   Cycle(R/I)              541 non-null    int64  
 10  Cycle length(days)      541 non-null    int64  
 11  Marraige Status (Yrs)   540 non-null    float64
 12  Pregnant(Y/N)           541 non-null    int64  
 13  No. of abortions        541 non-null    int64  
 14    I   beta-HCG(mIU/mL)  541 non-null    fl

In [8]:
df = df.dropna()

In [9]:
df.head()

PCOS (Y/N)   Age (yrs)  Weight (Kg)  Height(Cm)    BMI  Blood Group  \
0           0          28         44.6        152.0  19.3           15   
1           0          36         65.0        161.5  24.9           15   
2           1          33         68.8        165.0  25.3           11   
3           0          37         65.0        148.0  29.7           13   
4           0          25         52.0        161.0  20.1           11   

   Pulse rate(bpm)   RR (breaths/min)  Hb(g/dl)  Cycle(R/I)  ...  \
0                78                22     10.48           2  ...   
1                74                20     11.70           2  ...   
2                72                18     11.80           2  ...   
3                72                20     12.00           2  ...   
4                72                18     10.00           2  ...   

   Pimples(Y/N)  Fast food (Y/N)  Reg.Exercise(Y/N)  BP _Systolic (mmHg)  \
0             0              1.0                  0                  110   
1             0              0.0                  0                  120   
2             1              1.0                  0                  120   
3             0              0.0                  0                  120   
4             0              0.0                  0                  120   

   BP _Diastolic (mmHg)  Follicle No. (L)  Follicle No. (R)  \
0                    80                 3                 3   
1                    70                 3                 5   
2                    80                13                15   
3                    70                 2                 2   
4                    80                 3                 4   

   Avg. F size (L) (mm)  Avg. F size (R) (mm)  Endometrium (mm)  
0                  18.0                  18.0               8.5  
1                  15.0                  14.0               3.7  
2                  18.0                  20.0              10.0  
3                  15.0                  14.0               7.5  
4                  16.0                  14.0               7.0  

[5 rows x 40 columns]

In [10]:
df.dropna()

PCOS (Y/N)   Age (yrs)  Weight (Kg)  Height(Cm)    BMI  Blood Group  \
0             0          28         44.6      152.000  19.3           15   
1             0          36         65.0      161.500  24.9           15   
2             1          33         68.8      165.000  25.3           11   
3             0          37         65.0      148.000  29.7           13   
4             0          25         52.0      161.000  20.1           11   
..          ...         ...          ...          ...   ...          ...   
536           0          35         50.0      164.592  18.5           17   
537           0          30         63.2      158.000  25.3           15   
538           0          36         54.0      152.000  23.4           13   
539           0          27         50.0      150.000  22.2           15   
540           1          23         82.0      165.000  30.1           13   

     Pulse rate(bpm)   RR (breaths/min)  Hb(g/dl)  Cycle(R/I)  ...  \
0                  78                22     10.48           2  ...   
1                  74                20     11.70           2  ...   
2                  72                18     11.80           2  ...   
3                  72                20     12.00           2  ...   
4                  72                18     10.00           2  ...   
..                ...               ...       ...         ...  ...   
536                72                16     11.00           2  ...   
537                72                18     10.80           2  ...   
538                74                20     10.80           2  ...   
539                74                20     12.00           4  ...   
540                80                20     10.20           4  ...   

     Pimples(Y/N)  Fast food (Y/N)  Reg.Exercise(Y/N)  BP _Systolic (mmHg)  \
0               0              1.0                  0                  110   
1               0              0.0                  0                  120   
2               1              1.0                  0                  120   
3               0              0.0                  0                  120   
4               0              0.0                  0                  120   
..            ...              ...                ...                  ...   
536             0              0.0                  0                  110   
537             0              0.0                  0                  110   
538             0              0.0                  0                  110   
539             1              0.0                  0                  110   
540             1              1.0                  0                  120   

     BP _Diastolic (mmHg)  Follicle No. (L)  Follicle No. (R)  \
0                      80                 3                 3   
1                      70                 3                 5   
2                      80                13                15   
3                      70                 2                 2   
4                      80                 3                 4   
..                    ...               ...               ...   
536                    70                 1                 0   
537                    70                 9                 7   
538                    80                 1                 0   
539                    70                 7                 6   
540                    70                 9                10   

     Avg. F size (L) (mm)  Avg. F size (R) (mm)  Endometrium (mm)  
0                    18.0                  18.0               8.5  
1                    15.0                  14.0               3.7  
2                    18.0                  20.0              10.0  
3                    15.0                  14.0               7.5  
4                    16.0                  14.0               7.0  
..                    ...                   ...               ...  
536                  17.5                  10.0          

In [11]:
df.isna().sum()

PCOS (Y/N)                0
 Age (yrs)                0
Weight (Kg)               0
Height(Cm)                0
BMI                       0
Blood Group               0
Pulse rate(bpm)           0
RR (breaths/min)          0
Hb(g/dl)                  0
Cycle(R/I)                0
Cycle length(days)        0
Marraige Status (Yrs)     0
Pregnant(Y/N)             0
No. of abortions          0
  I   beta-HCG(mIU/mL)    0
FSH(mIU/mL)               0
LH(mIU/mL)                0
FSH/LH                    0
Hip(inch)                 0
Waist(inch)               0
Waist:Hip Ratio           0
TSH (mIU/L)               0
PRL(ng/mL)                0
Vit D3 (ng/mL)            0
PRG(ng/mL)                0
RBS(mg/dl)                0
Weight gain(Y/N)          0
hair growth(Y/N)          0
Skin darkening (Y/N)      0
Hair loss(Y/N)            0
Pimples(Y/N)              0
Fast food (Y/N)           0
Reg.Exercise(Y/N)         0
BP _Systolic (mmHg)       0
BP _Diastolic (mmHg)      0
Follicle No. (L)    

In [12]:
df.dtypes

PCOS (Y/N)                  int64
 Age (yrs)                  int64
Weight (Kg)               float64
Height(Cm)                float64
BMI                       float64
Blood Group                 int64
Pulse rate(bpm)             int64
RR (breaths/min)            int64
Hb(g/dl)                  float64
Cycle(R/I)                  int64
Cycle length(days)          int64
Marraige Status (Yrs)     float64
Pregnant(Y/N)               int64
No. of abortions            int64
  I   beta-HCG(mIU/mL)    float64
FSH(mIU/mL)               float64
LH(mIU/mL)                float64
FSH/LH                    float64
Hip(inch)                   int64
Waist(inch)                 int64
Waist:Hip Ratio           float64
TSH (mIU/L)               float64
PRL(ng/mL)                float64
Vit D3 (ng/mL)            float64
PRG(ng/mL)                float64
RBS(mg/dl)                float64
Weight gain(Y/N)            int64
hair growth(Y/N)            int64
Skin darkening (Y/N)        int64
Hair loss(Y/N)

In [13]:
X = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
print(X_train)

[[ 31.   55.  156.  ...  18.   20.    8.5]
 [ 44.   56.  142.  ...  19.   19.    6. ]
 [ 33.   60.  152.  ...  16.   16.   10.2]
 ...
 [ 23.   54.  158.  ...  15.   13.   10. ]
 [ 31.   50.  152.  ...  15.   20.    7.5]
 [ 36.   65.  154.  ...   7.5   4.5   5.4]]


In [16]:
print(y_train)

[1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 1 0 1 1 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 1 0
 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 0 1 1 0
 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1
 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0
 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0
 0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0
 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 0 1 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0
 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [44]:
#ANN model
import tensorflow as tf
ann = tf.keras.models.Sequential()

In [45]:
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=500, activation='relu'))
# ann.add(tf.keras.layers.Dropout(0.20))
ann.add(tf.keras.layers.Dense(units=1000, activation='relu'))
# ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
# ann.add(tf.keras.layers.Dropout(0.20))
ann.add(tf.keras.layers.Dense(units=500, activation='relu'))
# ann.add(tf.keras.layers.Dropout(0.20))
# ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
# ann.add(tf.keras.layers.Dropout(0.40))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#activation function for non-binary classification is softmax

In [46]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#loss for non-binary classification is 'categorical_crossentropy'

In [47]:
from keras.callbacks import ModelCheckpoint, EarlyStopping
es = EarlyStopping(monitor='accuracy', min_delta=0.01, patience=3, verbose=1, mode='auto')
mc = ModelCheckpoint(monitor='accuracy', filepath = "D:\Projects\Datasets\PCOS_data\Best_model.h5", verbose=1, save_best_only = True, mode='auto')
cd = [es, mc]

In [48]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100, steps_per_epoch=10, verbose = 1)

Epoch 1/100
10/10 [==============================] - 1s 11ms/step - loss: 0.4480 - accuracy: 0.8125
Epoch 2/100
10/10 [==============================] - 0s 10ms/step - loss: 0.3066 - accuracy: 0.8779
Epoch 3/100
10/10 [==============================] - 0s 10ms/step - loss: 0.1957 - accuracy: 0.9241
Epoch 4/100
10/10 [==============================] - 0s 11ms/step - loss: 0.1107 - accuracy: 0.9688
Epoch 5/100
10/10 [==============================] - 0s 11ms/step - loss: 0.1124 - accuracy: 0.9736
Epoch 6/100
10/10 [==============================] - 0s 9ms/step - loss: 0.0472 - accuracy: 0.9802
Epoch 7/100
10/10 [==============================] - 0s 12ms/step - loss: 0.0553 - accuracy: 0.9835
Epoch 8/100
10/10 [==============================] - 0s 11ms/step - loss: 0.0293 - accuracy: 0.9906
Epoch 9/100
10/10 [==============================] - 0s 12ms/step - loss: 0.0182 - accuracy: 0.9934
Epoch 10/100
10/10 [==============================] - 0s 11ms/step - loss: 0.0159 - accuracy: 0.9934


In [49]:
y_pred = ann.predict(X_test)

4/4 [==============================] - 0s 7ms/step


In [50]:
y_pred

array([[3.37404907e-16],
       [9.99740303e-01],
       [9.09038903e-12],
       [5.12361050e-01],
       [2.80483641e-06],
       [4.93249033e-08],
       [1.00000000e+00],
       [5.67702063e-09],
       [9.99530137e-01],
       [1.00000000e+00],
       [1.22453612e-08],
       [1.87641444e-10],
       [2.28069366e-05],
       [1.37234525e-14],
       [9.53990706e-11],
       [4.60688909e-09],
       [9.93122251e-10],
       [9.99769151e-01],
       [8.91967113e-15],
       [3.82150445e-09],
       [3.46631314e-15],
       [1.00000000e+00],
       [4.00871336e-10],
       [1.21765473e-10],
       [1.17678698e-16],
       [3.26886140e-09],
       [1.49726260e-12],
       [9.99999702e-01],
       [1.55933773e-12],
       [9.99997556e-01],
       [1.41783702e-15],
       [8.04480248e-14],
       [1.12183867e-02],
       [9.34737386e-16],
       [4.18660462e-12],
       [9.99999642e-01],
       [9.69080927e-10],
       [9.73171055e-01],
       [7.53217696e-15],
       [1.48919970e-03],


In [51]:
y_pred = (y_pred > 0.5)

In [52]:
print(np.concatenate((y_pred.reshape(len(X_test), 1), y_test.reshape(len(X_test), 1)), 1))

[[0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]]


In [53]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [54]:
print(confusion_matrix(y_test, y_pred))

[[72  9]
 [ 2 25]]


In [55]:
print(accuracy_score(y_test, y_pred))

0.8981481481481481


In [56]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.89      0.93        81
           1       0.74      0.93      0.82        27

    accuracy                           0.90       108
   macro avg       0.85      0.91      0.87       108
weighted avg       0.91      0.90      0.90       108

